# Generated by Django 4.2.7 on 2023-11-15 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_bloodbank_blooddonor_bloodrequest_review_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pints_needed', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='backend.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('contact_information', models.JSONField()),
                ('address', models.TextField()),
                ('medical_history', models.TextField()),
                ('available', models.BooleanField()),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='backend.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('contact_information', models.JSONField()),
                ('address', models.TextField()),
                ('medical_history', models.TextField()),
                ('need_blood', models.BooleanField()),
                ('preferred_source', models.CharField(max_length=20)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='backend.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('blood_bank', 'Blood Bank'), ('blood_recipient', 'Blood Recipient'), ('donor', 'Donor')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='contact_information',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='BloodDonor',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='backend.userprofile'),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='blood_stock',
            field=models.ManyToManyField(related_name='hospitals', to='backend.bloodtype'),
        ),
    ]
