# Generated by Django 4.2.7 on 2023-11-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_bloodtype_donationrequest_donor_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='blood_stock',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='operational_hours',
            field=models.CharField(default='9 AM - 5 PM', max_length=255),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='phone',
            field=models.CharField(default='+234 7858559023', max_length=15),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='services_provided',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='backend.donor'),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='request_type',
            field=models.CharField(choices=[('individual', 'From Individual (Donor)'), ('blood_bank', 'From Blood Bank')], default='individual', max_length=15),
        ),
        migrations.AddField(
            model_name='donor',
            name='donation_type',
            field=models.CharField(choices=[('free', 'Free Donation'), ('token', 'Token Donation')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(default='+234 7858559023', max_length=15),
        ),
        migrations.DeleteModel(
            name='BloodType',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
